spring:
  application:
    name: duty-bot-2
  datasource:
    url: jdbc:mysql://localhost:3306/testdutybot2
#    url: jdbc:mysql://mysql:3306/main
    username: temic
    password: 505606
  jpa:
    generate-ddl: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 1488
logging:
  level:
    root: info
dutybot2:
  executeDate: 2024-04-24
  name: DutyBot2
  token: 6832595206:AAFLifUdptMq_9nK_U_Xk1k7FZ8dJxmCPvQ
